# Generated by Django 5.2.14 on 2026-06-03 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_disbursementrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disbursementrequest",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
