# Generated by Django 5.2.14 on 2026-06-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_payment_fields"),
        ("marketplace", "0002_produce_egg_size_produce_type_expanded"),
    ]

    operations = []
