# Generated by Django 5.2.14 on 2026-06-05 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_merge_20260604_2358"),
        ("marketplace", "0003_produce_egg_size_farm_nullable"),
    ]

    operations = []
