# Generated by Django 5.2.14 on 2026-06-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_merge_20260605_0014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produce",
            name="egg_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small (< 53g)"),
                    ("medium", "Medium (53–63g)"),
                    ("large", "Large (63–73g)"),
                    ("extra_large", "Extra Large (> 73g)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="produce",
            name="produce_type",
            field=models.CharField(
                choices=[
                    ("broilers", "Broilers"),
                    ("eggs", "Eggs"),
                    ("layers", "Layer Birds"),
                    ("day_old", "Day-old Chicks"),
                    ("smoked", "Smoked Chicken"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
