# Generated by Django 5.2.14 on 2026-06-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_order_payment_method"),
        ("marketplace", "0005_alter_produce_egg_size_alter_produce_produce_type"),
    ]

    operations = []
