# Generated by Django 5.2.14 on 2026-06-05 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0005_alter_farm_flock_type"),
        ("marketplace", "0007_expand_payment_methods"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="produce",
            name="accepts_cash_on_delivery",
        ),
        migrations.RemoveField(
            model_name="produce",
            name="accepts_instant_payment",
        ),
        migrations.AlterField(
            model_name="produce",
            name="egg_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("jumbo", "Jumbo"),
                ],
                help_text="Only applicable when produce_type is eggs",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="produce",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="farms.farm",
            ),
        ),
        migrations.AlterField(
            model_name="produce",
            name="produce_type",
            field=models.CharField(
                choices=[
                    ("broilers", "Broilers"),
                    ("eggs", "Eggs"),
                    ("layers", "Layer Birds"),
                    ("day_old", "Day-old Chicks"),
                    ("smoked", "Smoked Chicken"),
                    ("guinea_fowl", "Guinea Fowl"),
                    ("turkey", "Turkey"),
                    ("duck", "Duck"),
                    ("quail", "Quail"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
