# Generated by Django 5.2.14 on 2026-06-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_monitoring_officer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringofficerprofile",
            name="assigned_districts",
            field=models.JSONField(
                default=list, help_text="List of district names this officer covers"
            ),
        ),
        migrations.AlterField(
            model_name="monitoringofficerprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
