# Generated by Django 5.2.14 on 2026-06-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_monitoring_officer_role"),
        ("accounts", "0003_alter_monitoringofficerprofile_assigned_districts_and_more"),
    ]

    operations = []
