# Generated by Django 5.2.14 on 2026-06-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_merge_20260604_2122"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MonitoringOfficerProfile",
        ),
    ]
