# Generated by Django 5.2.14 on 2026-06-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0003_expand_flock_types_and_species_counts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="flock_type",
            field=models.CharField(
                choices=[
                    ("broilers", "Broilers"),
                    ("layers", "Layers"),
                    ("guinea_fowl", "Guinea Fowl"),
                    ("turkey", "Turkey"),
                    ("duck", "Duck"),
                    ("geese", "Geese"),
                    ("ostrich", "Ostrich"),
                    ("day_old_chicks", "Day-Old Chicks"),
                    ("hatchery", "Hatchery Only"),
                    ("poultry_and_hatchery", "Poultry + Hatchery"),
                    ("mixed", "Mixed Poultry"),
                ],
                max_length=20,
            ),
        ),
    ]
