# Generated by Django 5.2.14 on 2026-06-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_description_optional"),
        ("training", "0002_trainingmodule_webinar_fields"),
    ]

    operations = []
