# Generated by Django 5.2.14 on 2026-06-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_merge_20260604_2122"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingmodule",
            name="meeting_platform",
        ),
        migrations.RemoveField(
            model_name="trainingmodule",
            name="meeting_url",
        ),
        migrations.RemoveField(
            model_name="trainingmodule",
            name="scheduled_at",
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="module_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("pdf", "PDF Guide"),
                    ("webinar", "Webinar Recording"),
                    ("quiz", "Quiz"),
                ],
                max_length=20,
            ),
        ),
    ]
